## Numpy 기초연습문제

In [1]:
import numpy as np 

### 1. np.zeros를 이용하여 행이 3, 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 a가 되도록 한다.

In [2]:
a= np.zeros((3,4)) #np.zeros를 이용하여 행이 3, 열이 4인 ndarray를 생성
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### 2. 위에서 생성한 ndarray a에 대하여, 다중 for 문을 이용하여 아래와 같은 값을 갖도록 초기화하시오.
array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [3]:
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i, j] = i*4 + j + 1       #for문을 이용하여 새로운 값 지정하기 
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [4]:
num = 1
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i, j] =  num             #for문을 이용하여 새로운 값 지정하기 
        num += 1
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

### 3. 초기화한 a로부터 값 7을 꺼내도록 인덱싱하시오.

In [8]:
a[1,2]    #7을 꺼내도록 indexing

7.0

### 4. a에서 아래와 같이 둘째 행을 꺼내도록 인덱싱하시오. 단 차원이 유지되어야 한다. 

array([[5., 6., 7., 8.]])



In [9]:
a.shape #3행4열 

(3, 4)

In [11]:
a[[1],:]    #둘째행꺼내기 

array([[5., 6., 7., 8.]])

### 5. a에서 아래와 같이 둘째 열과 셋째 열이 나오도록 인덱싱하시오.

array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.]])

In [13]:
a[:,[1,2]]   #둘째열과 셋째 열이 나오도록 indexing

array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.]])

### 6. 아래와 같이 a에서 6보다 작거나 같은 값들이 나오도록 불리안 인덱싱을 하시오.

array([1., 2., 3., 4., 5., 6.])

In [16]:
result = np.asarray([a[i, j] for i in range(a.shape[0]) for  j in range(a.shape[1]) if a[i, j] <= 6]) #for문을 써서 6보다 작은 값이 나오도록 indexing 
result

array([1., 2., 3., 4., 5., 6.])

In [14]:
a[a <= 6]    #6보다 작은 값을 꺼내기 

array([1., 2., 3., 4., 5., 6.])

### 7.  np.random 패키지를 이용하여 0에서 1사이의 값이 무작위로 생성된, 행이 3 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 b가 되도록 한다.

In [17]:
b= np.random.random((3,4))    # b는 0에서 1사이 값이 무작위로 생성된 3행4열 
b

array([[0.54486535, 0.73963223, 0.96543055, 0.44124302],
       [0.36261598, 0.33904287, 0.44454703, 0.22833658],
       [0.32887896, 0.62930262, 0.8742291 , 0.43343464]])

### 8. a와 b의 요소곱을 하여 c에 저장하시오.

In [20]:
c= a*b #c는 a와 b곱하기 
c

array([[0.54486535, 1.47926447, 2.89629166, 1.76497206],
       [1.81307992, 2.03425723, 3.11182923, 1.82669266],
       [2.95991068, 6.29302615, 9.6165201 , 5.20121563]])

### 9. b의 전치행렬을 구하여 d에 저장하시오.

In [22]:
d = b.T     #d는 b의 전치행렬
d

array([[0.54486535, 0.36261598, 0.32887896],
       [0.73963223, 0.33904287, 0.62930262],
       [0.96543055, 0.44454703, 0.8742291 ],
       [0.44124302, 0.22833658, 0.43343464]])

In [24]:
d.shape  #d의 차원의 크기 구하기 

(4, 3)

### 10. a와 d에 대하여 각 차원의 크기를 출력하시오.

In [26]:
print(a.shape, d.shape)    #a와d의 차원의 크기

(3, 4) (4, 3)


### 11. a와 d의 행렬곱을 계산하여 e에 저장하시오.

In [27]:
e = a.dot(d)    #e는 a와d의 행렬의 곱
e

array([[ 6.68539354,  3.28768915,  5.94391004],
       [17.45007817,  8.78585904, 15.0072913 ],
       [28.21476279, 14.28402892, 24.07067256]])

### 12. e에 대하여 각 열의 합을 계산하시오.

In [29]:
np.sum(e, axis=1)      #e의 각 열의 합 계산하기 

array([15.91699274, 41.24322851, 66.56946428])